[[search_dirs]]
path = "/home/brian/projects"
depth = 10

[[search_dirs]]
path = "/home/brian/nixconfig"
depth = 1

[[search_dirs]]
path = "/home/brian/exercism"
depth = 2

[[search_dirs]]
path = "/home/brian/os-images"
depth = 2

